title: QingLe Zhang's Homepage
page-top-title: QingLe Zhang
top-section-bg-text: SlackWave Team (闲波小组)
home-subtitle: QingLe Zhang &ensp;|&ensp;张庆乐 (摸鱼小队长)
copyright-text: '&copy; QingLe Zhang 2024-2025. All Rights Reserved.'
