title: QingLe Zhang's Homepage
page-top-title: QingLe Zhang
top-section-bg-text: SlackWave Lab (闲波实验室)
home-subtitle: QingLe Zhang &ensp;|&ensp;张庆乐
copyright-text: '&copy; QingLe Zhang 2024-2025. All Rights Reserved.'
